### ISSUE TITLE
Fatal error: Class 'Syscover\Pulsar\Models\Package' not found

### ISSUE THREAD

**Issue by epileftro85** [syscover/crm#1]
hi, i want to test your crm but when i make `php artisan db:seed --class="CrmTableSeeder"` i get this error `Fatal error: Class 'Syscover\Pulsar\Models\Package' not found` i think is a problem of namespaces

**Comment by carlospalacin** [comment]
try to execute:

`php artisan optimize`

**Comment by epileftro85** [comment]
nop, the same result, even i ran clear-compiled

**Comment by carlospalacin** [comment]
Please install this package before crm package:

[https://github.com/syscover/pulsar](url)

regards!

**Comment by epileftro85** [comment]
hey tks for the answer

**Comment by carlospalacin** [comment]
your welcome
